//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matie_420_ZagirovAlmir.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Matie_420_ZagirovAlmirEntities2 : DbContext
    {
        public Matie_420_ZagirovAlmirEntities2()
            : base("name=Matie_420_ZagirovAlmirEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<RequestKval> RequestKval { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Service_Master> Service_Master { get; set; }
        public virtual DbSet<ServiceAppointment> ServiceAppointment { get; set; }
        public virtual DbSet<StatusKval> StatusKval { get; set; }
        public virtual DbSet<StatusService> StatusService { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tranzaktions> Tranzaktions { get; set; }
        public virtual DbSet<TypeService> TypeService { get; set; }
    }
}
