//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matie_420_ZagirovAlmir.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestKval
    {
        public int IDRequest { get; set; }
        public Nullable<int> IDMaster { get; set; }
        public string CurrentKval { get; set; }
        public Nullable<int> IDStatusKval { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual StatusKval StatusKval { get; set; }
    }
}
