//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matie_420_ZagirovAlmir.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAppointment
    {
        public int IDSerApp { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IDMaster { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> NumberOfqueu { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Master Master { get; set; }
        public virtual StatusService StatusService { get; set; }
    }
}
