//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matie_420_ZagirovAlmir.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Master
    {
        public int IDService_Master { get; set; }
        public Nullable<int> IDService { get; set; }
        public Nullable<int> IDMaster { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Service Service { get; set; }
    }
}
