//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matie_420_ZagirovAlmir.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranzaktions
    {
        public int IDTranz { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Payement { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
